version: '3.7'


networks:
  test:
    name: ${NAME}

services:
  ${NAME}:
    container_name: ${NAME}
    image: hyperledger/fabric-ca:latest
    labels:
      service: hyperledger-fabric
    command: sh -c 'fabric-ca-server start -b ${USERNAME}:${PASSWORD}'
    environment:
      - FABRIC_CA_SERVER_HOME=${WORKING_DIR}/servers/${NAME}
    volumes:
      - ${WORKING_DIR}/servers/${NAME}:${WORKING_DIR}/servers/${NAME}
    networks:
      - test
    ports:
      - ${PORT}:${PORT}
      - ${LISTENINGPORT}:${LISTENINGPORT}