version: '3.7'

networks:
  test:
    name: fabric_test


services:
  cli:
    container_name: cli
    image: hyperledger/fabric-tools:latest
    labels:
      service: hyperledger-fabric
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_LOGGING_SPEC=INFO
      - FABRIC_CFG_PATH=$PWD/organizations/ship1/peers/peer1
      #- FABRIC_LOGGING_SPEC=DEBUG
    working_dir: $PWD
    command: /bin/bash
    volumes:
        - $PWD/organizations:$PWD/organizations
        - $PWD:$PWD
    networks:
      - test