# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &${ORG}
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: ${ORG}MSP

        # ID to load the MSP definition as
        ID: ${ORG}MSP

        MSPDir: FILE/organizations/${ORG}/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('${ORG}MSP.admin', '${ORG}MSP.peer', '${ORG}MSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('${ORG}MSP.admin', '${ORG}MSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('${ORG}MSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('${ORG}MSP.peer')"
