NodeOUs:
    Enable: true
    ClientOUIdentifier:
        Certificate: cacerts/0-0-0-0-${PORT}.pem
        OrganizationalUnitIdentifier: client
    PeerOUIdentifier:
        Certificate: cacerts/0-0-0-0-${PORT}.pem
        OrganizationalUnitIdentifier: peer
    AdminOUIdentifier:
        Certificate: cacerts/0-0-0-0-${PORT}.pem
        OrganizationalUnitIdentifier: admin
    OrdererOUIdentifier:
        Certificate: cacerts/0-0-0-0-${PORT}.pem
        OrganizationalUnitIdentifier: orderer
