# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3.7'

volumes:
  ${NAMEPEER}.${ORG}:

networks:
  test:
    name: fabric_test


services:
  ${NAMEPEER}.${ORG}:
    container_name: ${NAMEPEER}.${ORG}
    image: hyperledger/fabric-peer:latest
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - FILE/organizations/${ORG}/peers/${NAMEPEER}:FILE/organizations/${ORG}/peers/${NAMEPEER}
      - ${DOCKER_SOCK}:/host/var/run/docker.sock